remove ruby version specification
hopefully removes this error on Travis;
```
ERROR:  Error installing html-proofer:
	activesupport requires Ruby version >= 2.2.2.
The command "gem install html-proofer" failed and exited with 1 during 
```